const DBKEY="TCA_V2";let role="",me=null,current="";
const seed=()=>{let students={};for(let c=1;c<=8;c++){students[c]=[];for(let i=1;i<=100;i++)students[c].push({id:`C${c}-${String(i).padStart(2,"0")}`,name:`Student ${c}-${i}`,father:`Father ${i}`,class:String(c)})}return{students,teachers:[],attendance:{},marks:{},dates:[],times:[]}};
let db=JSON.parse(localStorage.getItem(DBKEY)||"null")||seed();function save(){localStorage.setItem(DBKEY,JSON.stringify(db))}
const $=id=>document.getElementById(id);function show(id){["role","login","dashboard","modulePage"].forEach(x=>$(x).classList.toggle("hide",x!==id))}
function openLogin(r){role=r;["student","teacher","admin"].forEach(x=>$(x+"Form").classList.toggle("hide",x!==r));$("loginHeading").textContent=r==="student"?"Student Login":r==="teacher"?"Teacher Login":"Admin Login";$("loginSub").textContent=r==="student"?"Enter your student details":r==="teacher"?"Enter your teacher details":"Enter administrator details";show("login")}
function doLogin(){
 let id=$("uid").value.trim(),pass=$("pass").value.trim();if(!id||!pass){alert("Please enter ID and password.");return}
 if(role==="student"){let n=$("stName").value.trim(),f=$("stFather").value.trim(),c=$("stClass").value;if(!n||!f||!c){alert("Fill Student Name, Father Name and Class.");return}me={name:n,father:f,class:c,id:id}}
 if(role==="teacher"){let n=$("teName").value.trim(),c=$("teClass").value;if(!n||!c){alert("Fill Teacher Name and Assigned Class.");return}me={name:n,class:c,id:id}}
 if(role==="admin"){let n=$("adName").value.trim()||"School Admin";me={name:n,id:id}}
 renderDash();show("dashboard")}
function renderDash(){["studentPanel","teacherPanel","adminPanel"].forEach(x=>$(x).classList.add("hide"));$("roleLabel").textContent=role.toUpperCase();$("hello").textContent=`Welcome, ${me.name}`;$("sub").textContent=role==="student"?`Class ${me.class} • ID ${me.id}`:role==="teacher"?`Assigned Class ${me.class} • ID ${me.id}`:"Full school administration";$(role+"Panel").classList.remove("hide");if(role==="student")stats()}
function logout(){role="";me=null;show("role")}
function today(){return new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"2-digit",year:"numeric"})}
function iso(){return new Date().toISOString().slice(0,10)}
function stats(){let arr=db.attendance[me.id]||[];let p=arr.filter(x=>x.present).length,a=arr.length-p,t=arr.length;$("sp").textContent=p;$("sa").textContent=a;$("spercent").textContent=t?Math.round(p/t*100)+"%":"0%"}
function module(m){current=m;$("moduleTitle").textContent=titles[m]||m;$("moduleBody").innerHTML=bodies[m]();show("modulePage")}
const titles={studentAttendance:"My Attendance",studentMarks:"My Test Marks",studentDate:"Date Sheet",studentTime:"Time Table",studentProfile:"My Profile",takeAttendance:"Daily Attendance",enterMarks:"Enter Test Marks",manageDate:"Manage Date Sheet",manageTime:"Manage Time Table",classStudents:"My Students",adminStudents:"Student Management",adminTeachers:"Teacher Management",adminAttendance:"Attendance Reports",adminMarks:"Marks Reports",adminDate:"School Date Sheet",adminTime:"School Time Table"};
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const bodies={
studentAttendance:()=>{let a=db.attendance[me.id]||[];return `<h3>Attendance: ${a.filter(x=>x.present).length} Present / ${a.length} Total</h3><table><tr><th>Date</th><th>Status</th></tr>${a.map(x=>`<tr><td>${x.date}</td><td>${x.present?"Present":"Absent"}</td></tr>`).join("")||"<tr><td colspan=2 class=empty>No attendance recorded yet.</td></tr>"}</table>`},
studentMarks:()=>`<table><tr><th>Test</th><th>Subject</th><th>Marks</th></tr>${(db.marks[me.id]||[]).map(x=>`<tr><td>${esc(x.test)}</td><td>${esc(x.subject)}</td><td>${esc(x.marks)}</td></tr>`).join("")||"<tr><td colspan=3 class=empty>No marks published yet.</td></tr>"}</table>`,
studentDate:()=>dateTable(me.class),studentTime:()=>timeTable(me.class),
studentProfile:()=>`<p><b>Name:</b> ${esc(me.name)}</p><p><b>Father Name:</b> ${esc(me.father)}</p><p><b>Class:</b> ${esc(me.class)}</p><p><b>Student ID:</b> ${esc(me.id)}</p>`,
takeAttendance:()=>{let s=db.students[me.class]||[];return `<p><b>Today's date: ${today()}</b></p>${s.map(x=>`<div class=row><span>${x.id} — ${esc(x.name)}</span><button class=pill id="att-${x.id}" onclick="flipAtt('${x.id}',this)">Present</button></div>`).join("")}<button class=save onclick="saveAttendance()">Save Attendance</button>`},
enterMarks:()=>{let s=db.students[me.class]||[];return `<input id=mt placeholder="Test Name"><input id=ms placeholder="Subject"><table><tr><th>Student</th><th>Marks</th></tr>${s.map(x=>`<tr><td>${esc(x.name)}</td><td><input data-mid="${x.id}" placeholder="0"></td></tr>`).join("")}</table><button class=save onclick="saveMarks()">Save Marks</button>`},
manageDate:()=>dateManager(me.class),manageTime:()=>timeManager(me.class),classStudents:()=>studentTable(me.class),
adminStudents:()=>{let c=prompt("Enter class 1-8");if(!/^[1-8]$/.test(c))return "<p class=empty>Select a class from 1 to 8.</p>";return studentTable(c)+`<hr><input id=ns placeholder="Student name"><input id=nf placeholder="Father name"><button class=save onclick="addStudent(${c})">Add Student</button>`},
adminTeachers:()=>`<input id=tn placeholder="Teacher name"><select id=tc><option value="">Class</option>${[1,2,3,4,5,6,7,8].map(c=>`<option>${c}</option>`).join("")}</select><input id=tid placeholder="Teacher ID"><button class=save onclick="addTeacher()">Create Teacher</button><table><tr><th>Name</th><th>Class</th><th>ID</th></tr>${db.teachers.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.class}</td><td>${esc(x.id)}</td></tr>`).join("")}</table>`,
adminAttendance:()=>[1,2,3,4,5,6,7,8].map(c=>{let s=db.students[c]||[];let total=0,p=0;s.forEach(x=>(db.attendance[x.id]||[]).forEach(a=>{total++;if(a.present)p++}));return `<div class=row><b>Class ${c}</b><span>${total?Math.round(p/total*100):0}% recorded attendance</span></div>`}).join(""),
adminMarks:()=>`<p>Marks are stored student-wise and can be reviewed by opening a class through Student Management.</p>`,
adminDate:()=>dateManager("ALL"),adminTime:()=>timeManager("ALL")
};
function studentTable(c){let s=db.students[c]||[];return `<table><tr><th>ID</th><th>Name</th><th>Father</th><th>Class</th></tr>${s.map(x=>`<tr><td>${x.id}</td><td>${esc(x.name)}</td><td>${esc(x.father)}</td><td>${x.class}</td></tr>`).join("")}</table>`}
function dateTable(c){let a=db.dates.filter(x=>x.class===c||x.class==="ALL");return `<table><tr><th>Class</th><th>Subject</th><th>Date</th><th>Time</th></tr>${a.map(x=>`<tr><td>${x.class}</td><td>${esc(x.subject)}</td><td>${x.date}</td><td>${esc(x.time)}</td></tr>`).join("")||"<tr><td colspan=4 class=empty>No date sheet published.</td></tr>"}</table>`}
function timeTable(c){let a=db.times.filter(x=>x.class===c||x.class==="ALL");return `<table><tr><th>Class</th><th>Day</th><th>Period</th><th>Subject</th></tr>${a.map(x=>`<tr><td>${x.class}</td><td>${esc(x.day)}</td><td>${esc(x.period)}</td><td>${esc(x.subject)}</td></tr>`).join("")||"<tr><td colspan=4 class=empty>No timetable published.</td></tr>"}</table>`}
function dateManager(c){return `<input id=dsC placeholder="Class (1-8 or ALL)" value="${c}"><input id=dsS placeholder="Subject"><input id=dsD type=date><input id=dsT placeholder="Time"><button class=save onclick="addDate()">Publish Date Sheet Entry</button>${dateTable(c)}`}
function timeManager(c){return `<input id=ttC placeholder="Class (1-8 or ALL)" value="${c}"><input id=ttD placeholder="Day"><input id=ttP placeholder="Period"><input id=ttS placeholder="Subject"><button class=save onclick="addTime()">Publish Timetable Period</button>${timeTable(c)}`}
let tempAtt={};function flipAtt(id,b){tempAtt[id]=!tempAtt[id];b.textContent=tempAtt[id]?"Present":"Absent";b.style.opacity=tempAtt[id]?1:.55}
function saveAttendance(){let s=db.students[me.class]||[],d=iso();s.forEach(x=>{let a=db.attendance[x.id]||[];a=a.filter(y=>y.date!==d);a.push({date:d,present:!!tempAtt[x.id]});db.attendance[x.id]=a});save();tempAtt={};alert("Attendance saved for "+today());module("takeAttendance")}
function saveMarks(){let test=$("mt").value.trim(),sub=$("ms").value.trim();if(!test||!sub){alert("Enter test name and subject.");return}let s=db.students[me.class]||[];s.forEach(x=>{let el=document.querySelector(`[data-mid="${x.id}"]`);if(el&&el.value!==""){db.marks[x.id]=db.marks[x.id]||[];db.marks[x.id].push({test,subject:sub,marks:el.value})}});save();alert("Marks saved.");module("enterMarks")}
function addDate(){let c=$("dsC").value.trim(),s=$("dsS").value.trim(),d=$("dsD").value,t=$("dsT").value.trim();if(!c||!s||!d){alert("Fill class, subject and date.");return}db.dates.push({class:c,subject:s,date:d,time:t});save();alert("Date sheet published.");module(current)}
function addTime(){let c=$("ttC").value.trim(),d=$("ttD").value.trim(),p=$("ttP").value.trim(),s=$("ttS").value.trim();if(!c||!d||!p||!s){alert("Fill all timetable fields.");return}db.times.push({class:c,day:d,period:p,subject:s});save();alert("Timetable published.");module(current)}
function addStudent(c){let n=$("ns").value.trim(),f=$("nf").value.trim();if(!n||!f)return alert("Enter student and father name.");let id=`C${c}-${String((db.students[c]||[]).length+1).padStart(2,"0")}`;db.students[c].push({id,name:n,father:f,class:String(c)});save();alert("Student added. ID: "+id);module("adminStudents")}
function addTeacher(){let n=$("tn").value.trim(),c=$("tc").value,id=$("tid").value.trim();if(!n||!c||!id)return alert("Fill teacher name, class and ID.");db.teachers.push({name:n,class:c,id});save();alert("Teacher account created.");module("adminTeachers")}
function tick(){let d=new Date();$("clock").textContent=d.toLocaleDateString("en-IN",{weekday:"short",day:"2-digit",month:"short",year:"numeric"})+" • "+d.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"});}
setInterval(tick,1000);tick();setTimeout(()=>$("app").classList.remove("hide"),1000);
